// Generated file, do NOT edit

export default [
  {
    input: 'var x = <div>one</div><div>two</div>;',
    id: '161c',
    name: '0001-161c.jsx',
    error: true,
    errorMessage:
      'Adjacent JSX elements must be wrapped in an enclosing tag (1:22)',
  },
  {
    input: '<a:b.c />',
    id: 'ece3',
    name: '0002-ece3.jsx',
    error: true,
    errorMessage: 'Unexpected token (1:4)',
  },
  {
    input: '<ns:div />',
    id: 'd152',
    name: '0003-d152.jsx',
    error: true,
    errorMessage: 'Unexpected token (1:3)',
  },
  {
    input: '<div ns:attr />',
    id: '8c97',
    name: '0004-8c97.jsx',
    error: true,
    errorMessage: 'Unexpected token (1:7)',
  },
  {
    input: '<a>{/* foo */}</a>',
    id: '87c4',
    name: '0005-87c4.jsx',
    error: false,
  },
  {
    input: '<!--a',
    id: 'e58e',
    name: '0006-e58e.jsx',
    error: false,
  },
  {
    input: '<a />',
    id: 'e20f',
    name: '0007-e20f.jsx',
    error: false,
  },
  {
    input: '<n:a n:v />',
    id: 'bbc9',
    name: '0008-bbc9.jsx',
    error: false,
  },
  {
    input: '<a n:foo="bar"> {value} <b><c /></b></a>',
    id: '5240',
    name: '0009-5240.jsx',
    error: false,
  },
  {
    input: '<a b={" "} c=" " d="&amp;" e="&ampr;" />',
    id: 'fb6b',
    name: '0010-fb6b.jsx',
    error: false,
  },
  {
    input: '<a\n/>',
    id: 'b127',
    name: '0011-b127.jsx',
    error: false,
  },
  {
    input: '<日本語></日本語>',
    id: '912c',
    name: '0012-912c.jsx',
    error: false,
  },
  {
    input: '<AbC-def\n  test="&#x0026;&#38;">\nbar\nbaz\n</AbC-def>',
    id: 'e776',
    name: '0013-e776.jsx',
    error: false,
  },
  {
    input: '<a b={x ? <c /> : <d />} />',
    id: 'b2d2',
    name: '0014-b2d2.jsx',
    error: false,
  },
  {
    input: '<a>{}</a>',
    id: '1c64',
    name: '0015-1c64.jsx',
    error: false,
  },
  {
    input: '<a>{/* this is a comment */}</a>',
    id: '30fa',
    name: '0016-30fa.jsx',
    error: false,
  },
  {
    input: '<div>@test content</div>',
    id: '5bfe',
    name: '0017-5bfe.jsx',
    error: false,
  },
  {
    input: '<div><br />7x invalid-js-identifier</div>',
    id: 'c189',
    name: '0018-c189.jsx',
    error: false,
  },
  {
    input: '<LeftRight left=<a /> right=<b>monkeys /{">"} gorillas</b> />',
    id: 'c21b',
    name: '0019-c21b.jsx',
    error: false,
  },
  {
    input: '<LeftRight left=<a /> right=<b>monkeys /&gt; gorillas</b> />',
    id: '2386',
    name: '0020-2386.jsx',
    error: false,
  },
  {
    input: '<a.b></a.b>',
    id: '648f',
    name: '0021-648f.jsx',
    error: false,
  },
  {
    input: '<a.b.c></a.b.c>',
    id: '2b2b',
    name: '0022-2b2b.jsx',
    error: false,
  },
  {
    input: '(<div />) < x;',
    id: 'f709',
    name: '0023-f709.jsx',
    error: false,
  },
  {
    input: '<div {...props} />',
    id: '8dcd',
    name: '0024-8dcd.jsx',
    error: false,
  },
  {
    input: '<div {...props} post="attribute" />',
    id: 'd44b',
    name: '0025-d44b.jsx',
    error: false,
  },
  {
    input: '<div pre="leading" pre2="attribute" {...props}></div>',
    id: '8c19',
    name: '0026-8c19.jsx',
    error: false,
  },
  {
    input: '<A aa={aa.bb.cc} bb={bb.cc.dd}><div>{aa.b}</div></A>',
    id: 'b6c2',
    name: '0027-b6c2.jsx',
    error: false,
  },
  {
    input: '<><div></div></>',
    id: 'ea7d',
    name: '0028-ea7d.jsx',
    error: false,
  },
  {
    input: '<p>foo <a href="test"> bar</a> baz</p> ;',
    id: '5737',
    name: '0029-5737.jsx',
    error: false,
  },
  {
    input: '<div>{<div {...test} />}</div>',
    id: '450d',
    name: '0030-450d.jsx',
    error: false,
  },
  {
    input: '<div>{ {a} }</div>',
    id: 'b330',
    name: '0031-b330.jsx',
    error: false,
  },
  {
    input: '<div>/text</div>',
    id: 'e087',
    name: '0032-e087.jsx',
    error: false,
  },
  {
    input: '<div>{a}{b}</div>',
    id: 'd15f',
    name: '0033-d15f.jsx',
    error: false,
  },
  {
    input: '<div pre="leading" {...props} />',
    id: '75fb',
    name: '0034-75fb.jsx',
    error: false,
  },
  {
    input:
      '<path d="M230 80\n\t\tA 45 45, 0, 1, 0, 275 125 \r\n    L 275 80 Z"/>',
    id: '2f55',
    name: '0035-2f55.jsx',
    error: false,
  },
  {
    input: '<LeftRight left=<a /> right=<b>monkeys /> gorillas</b> />',
    id: '913f',
    name: '0036-913f.jsx',
    error: true,
    errorMessage:
      'Unexpected token `>`. Did you mean `&gt;` or `{">"}`? (1:40)',
  },
  {
    input: '<A>foo{</A>',
    id: 'e89b',
    name: '0037-e89b.jsx',
    error: true,
    errorMessage: 'Unexpected token (1:8)',
  },
  {
    input: '<A>foo<</A>',
    id: '7a35',
    name: '0038-7a35.jsx',
    error: true,
    errorMessage: 'Unexpected token (1:7)',
  },
  {
    input: '<A>foo}</A>',
    id: '8827',
    name: '0039-8827.jsx',
    error: true,
    errorMessage:
      'Unexpected token `}`. Did you mean `&rbrace;` or `{"}"}`? (1:6)',
  },
  {
    input: '<A>foo></A>',
    id: '4dc3',
    name: '0040-4dc3.jsx',
    error: true,
    errorMessage: 'Unexpected token `>`. Did you mean `&gt;` or `{">"}`? (1:6)',
  },
  {
    input: '<A>foo{"{"}</A>',
    id: '35d9',
    name: '0041-35d9.jsx',
    error: false,
  },
  {
    input: '<A>foo{"<"}</A>',
    id: '491a',
    name: '0042-491a.jsx',
    error: false,
  },
  {
    input: '<A>foo{"}"}</A>',
    id: '690b',
    name: '0043-690b.jsx',
    error: false,
  },
  {
    input: '<A>foo&rbrace;</A>',
    id: '16f0',
    name: '0044-16f0.jsx',
    error: false,
  },
  {
    input: '<A>foo{">"}</A>',
    id: '7784',
    name: '0045-7784.jsx',
    error: false,
  },
  {
    input: '<A>foo&gt;</A>',
    id: '8011',
    name: '0046-8011.jsx',
    error: false,
  },
  {
    input: 'function*it(){yield <a></a>}',
    id: 'fdd5',
    name: '0047-fdd5.jsx',
    error: false,
  },
]
